name: Deploy (Terraform)

on:
  push:
    branches: [ main, master, testes, testes-2 ]
  workflow_dispatch:

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        working-directory: infra/terraform
        run: terraform init -input=false

      - name: Terraform Destroy (reset infra)
        working-directory: infra/terraform
        continue-on-error: true
        run: |
          echo "ðŸ§¨ Destroying previous infrastructure (if exists)..."
          terraform destroy -auto-approve -input=false || echo "No existing state to destroy"
          echo "âœ… Destroy step finished"

      - name: Terraform Re-Init (after destroy)
        working-directory: infra/terraform
        run: terraform init -input=false

      - name: Terraform Plan (fresh deploy)
        working-directory: infra/terraform
        run: terraform plan -input=false -var "image=${{ secrets.ECR_REGISTRY }}/${{ secrets.IMAGE_NAME }}:latest" -out=plan.tfplan

      - name: Terraform Apply (fresh infra)
        working-directory: infra/terraform
        run: terraform apply -input=false -auto-approve plan.tfplan
